Added useEventListener
svecosystem/runed pull request #7
Opened 2024-04-13 17:30 UTC by Hugos68

2024-04-14 01:10 UTC, huntabyte requested changes

2024-04-14 01:10 UTC, huntabyte commented on sites/docs/content/functions/use-event-listener.md
> +	const activeElement = useActiveElement();
Was this a leftover from the copy paste?

2024-04-14 14:04 UTC, Hugos68 commented
For some reason the example in the docs site is still broken 🤔

2024-04-22 12:24 UTC, huntabyte approved these changes

2024-04-22 12:28 UTC, merged